// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkzZtZ2YcE7bHRa6uqzc3ec5FOXa7wSIE',
    appId: '1:410337708306:web:a4dac007f5d2b2946c8bcb',
    messagingSenderId: '410337708306',
    projectId: 'bs-resume-creator',
    authDomain: 'bs-resume-creator.firebaseapp.com',
    storageBucket: 'bs-resume-creator.firebasestorage.app',
    measurementId: 'G-YX0JSPX6Q9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4SBnC_vMfHMtglz9Xc5A5YgXawHOzrGo',
    appId: '1:410337708306:android:55b91e98fdbcf62b6c8bcb',
    messagingSenderId: '410337708306',
    projectId: 'bs-resume-creator',
    storageBucket: 'bs-resume-creator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCktJBXuclM8TSnA8ap-KOsygoDE8ehtGY',
    appId: '1:410337708306:ios:63ab0ff4a7fc816e6c8bcb',
    messagingSenderId: '410337708306',
    projectId: 'bs-resume-creator',
    storageBucket: 'bs-resume-creator.firebasestorage.app',
    iosBundleId: 'zw.co.malvernbright.resumeCreator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCktJBXuclM8TSnA8ap-KOsygoDE8ehtGY',
    appId: '1:410337708306:ios:63ab0ff4a7fc816e6c8bcb',
    messagingSenderId: '410337708306',
    projectId: 'bs-resume-creator',
    storageBucket: 'bs-resume-creator.firebasestorage.app',
    iosBundleId: 'zw.co.malvernbright.resumeCreator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkzZtZ2YcE7bHRa6uqzc3ec5FOXa7wSIE',
    appId: '1:410337708306:web:6998acf2ea2a02096c8bcb',
    messagingSenderId: '410337708306',
    projectId: 'bs-resume-creator',
    authDomain: 'bs-resume-creator.firebaseapp.com',
    storageBucket: 'bs-resume-creator.firebasestorage.app',
    measurementId: 'G-DBLJEFP1V5',
  );
}
